### ISSUE TITLE
Include date info in last upload time

### ISSUE THREAD

**Issue by sboettcher** [RADAR-base/radar-prmt-android#113]
Here: https://github.com/RADAR-base/radar-prmt-android/blob/eb5aa553a6753189502fcf6ee3261790e0d6d82c/app/src/main/java/org/radarcns/detail/MainActivityViewImpl.kt#L42

i.e., in the string under "synchronisation"
![image](https://user-images.githubusercontent.com/5064873/107371584-b82d5b00-6ae4-11eb-94d6-6d14fe08a159.png)

**Comment by sboettcher** [comment]
If this could be included in one of the next releases, it would be really helpful. If we try to remotely debug connection problems with participants, it can be important to know when exactly the last contact was, and if it was more than one day ago the information currently given is a bit limited. Thanks!

**Comment by blootsvoets** [comment]
Thanks for reporting this. It sounds like a good update. Could you please create a PR? Changing https://github.com/RADAR-base/radar-prmt-android/blob/5d67fe14a402f86efc7213ba457c7b505610d3a8/app/src/main/java/org/radarcns/detail/MainActivityViewImpl.kt#L186 should do the trick?
