### ISSUE TITLE
Similar Android Sensor Interfaces

### ISSUE THREAD

**Issue by afolarin** [RADAR-base/radar-prmt-android#2]
With the objective of getting phone sensor data and hooking in additional wearable device sensors, I thought it worth a look at some existing open source applications in this space -- two of which are:

Relayr Proto iOT
https://github.com/relayr/android-proto-IoT  \* looks interesting, android app on Play store

Purple Robot
https://github.com/cbitstech/Purple-Robot *caveat that it's not being actively developed

/cc @MaximMoinat @herkulano @fnobilia

**Comment by fnobilia** [comment]
also this one http://emotionsense.org/code.html

**Comment by herkulano** [comment]
Relayr, looks really interesting, the application and the developer dashboard.

**Comment by MaximMoinat** [comment]
Moved to Confluent wiki for future reference
