### ISSUE TITLE
Implementing cellphone data collector

### ISSUE THREAD

**Issue by hesamsagha** [RADAR-base/radar-prmt-android#27]
- [x] #SMS/timeline (day/week/...)
- [x] #calls/timeline (day/week/...)
- [x] duration of calls
- [x] GPS location
- [x] App usage
- [x] Interaction time (not in standby)

**Comment by MaximMoinat** [comment]
Thanks Hesam. We will start by implementing the Aware Framework.
Could you check [the Aware documentation ](http://www.awareframework.com/communication/) whether all needed data can be gathered from this framework? Thanks

**Comment by hesamsagha** [comment]
yes, it seems it has everything needed.

**Comment by MaximMoinat** [comment]
Hesam, our idea at the moment is to read the call/sms log at regular intervals (e.g. once an hour). We will not need the Aware framework for this.
As a consequence, there can be a long delay between the call and sending the call records. To your knowledge, is it required for the researchers to immediately receive the records of any new calls/messages?

**Comment by hesamsagha** [comment]
I think we need to send it even with larger interval (1/day) [but it needs to be defined in the schema], nd no need for quick report. And I would say 'right', using Aware makes things more complicated if we don't need other functionalities.

**Comment by MaximMoinat** [comment]
All mentioned phone data collectors have been implemented, with the exception of the app usage. See the `phone-sensors` branch.
We are keeping this separate from the main dev branch at the moment, because calls and location add new permissions to the app that are unwanted in the pilot studies.

App usage is still a complicated item, because Android does not provide listeners for application launch actions. What level of detail is needed? The app names and the durations (in foreground+background)?

**Comment by afolarin** [comment]
@MaximMoinat can we include here the configurable aspect of the phone sensors, presently it's all or none. Also the original list is not the exhaustive set of sensors you have implemented and schematized?

**Comment by MaximMoinat** [comment]
We have indeed implemented more phone sensors than originally requested (acceleration, ambient light and battery level). Android sensors like magnetometer and barometer can be added easily.

The configurability of the phone sensors is part of the dynamic_services branch. This is still work in progress.

**Comment by MaximMoinat** [comment]
Individual sensors can be disabled by setting their update interval to 0, as described in the readme of the phone plugin: https://github.com/RADAR-base/radar-android-phone
