### ISSUE TITLE
Add timezone information

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/radar-prmt-android#44]
Having the timezone of a patient is incredibly useful for deducing daily patterns and activities. Probably the application should send information about the timezone that a patient is in. This is an incredibly large region, so we don't have to be too worried about privacy I suppose.

**Comment by blootsvoets** [comment]
Linked to RADAR-CNS/RADAR-Schemas#22.

**Comment by PiotrZakrzewski** [comment]
I will pick this one up

**Comment by blootsvoets** [comment]
Done in radar-android-application-status
