### ISSUE TITLE
Tablet compatibility

### ISSUE THREAD

**Issue by MaximMoinat** [RADAR-base/radar-prmt-android#65]
In the Google Play Store, the app is not available for tablets. This is caused by the [Google Play filters](https://developer.android.com/google/play/filters.html). 

Probably the cause is the restriction of the `<uses-feature>` in the manifest. Solution could be to add `android:required="false"` to each feature in the enabled plugins. See this answer on SO: https://stackoverflow.com/a/10444843

**Comment by MaximMoinat** [comment]
@yatharthranjan Could you comment whether this is indeed the issue you raised?

**Comment by yatharthranjan** [comment]
Yes indeed this is the issue.

**Comment by MaximMoinat** [comment]
Above fixes should solve the issue and display the app in the Play Store on tablets. Please check when a new release of the app is made.
