### ISSUE TITLE
Create a version of pRMT which has URL endpoints configurable

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/radar-prmt-android#66]
Create a version of pRMT which has URL endpoints configurable so that user can enter the URL and test the sending of data without the need to compile and build the app from source code. This will be useful for testing and RADAR-base Quickstart tutorials where people can just spin up the RADAR-Docker stack and start sending data immediately. 

This source code for this can be stored on a different branch in this repository and the app published on the playstore as pRMT-Quickstart or similar

**Comment by wsy19961129** [comment]
Hello, I am just wondering if this app pRMT-Quickstart still exists on playstore cause I didn't find it in playstore. Many thanks!

**Comment by yatharthranjan** [comment]
Hi @wsy19961129 , sorry this feature has not yet been implemented. However you can ask @nivemaham or @blootsvoets to remotely configure the officail pRMT on playstore to work with your deployment.

**Comment by nivemaham** [comment]
@yatharthranjan Just to update, I think the idea was to enable this through remote-config on Firebase.
We prefer not to maintain multiple distributions of the app. I would consider this done, except there is no separate distribution as a quick-start. 
Users can send data without compiling the app.
