### ISSUE TITLE
Send notification if wearable gets disconnected

### ISSUE THREAD

**Issue by blootsvoets** [RADAR-base/radar-prmt-android#99]
Send system notification whenever a hardware wearable gets disconnected, in order that participants are duly aware of this occurrence. With a configurable time period in firebase for when notifications are silent.

@yatharthranjan @zulqarnain343 is that correct?

**Comment by zulqarnain343** [comment]
@sboettcher is it same as you requested? With configurable time period we can make it silent during the night.

**Comment by sboettcher** [comment]
Yes exactly, that sounds good to me!
I am not too fluent in android notification coding, but here are some of my thoughts:
- The notification importance should be urgent as per [this table](https://developer.android.com/training/notify-user/channels.html#importance).
- Is the configurable time period necessary? There is a Do Not Disturb setting on pretty much any android starting with 5.0 right? Although I guess it is not a bad thing to have.
- There are some notifications that are not easily dismiss-able (I think the pRMT app even has one saying that it is running?), this should be one like that, that only gets dismissed when the device is reconnected.

**Comment by sboettcher** [comment]
Any updates on this? Can I help with anything?

**Comment by iampradeep-hr** [comment]
Can I work on this feature ?

**Comment by zulqarnain343** [comment]
this is implemented.

**Comment by afolarin** [comment]
Thanks for the offer @iampradeep-hr -- looks like we forgot to close this one :blush: . But you are welcome to get involved -- if you are interested, happy to flag some issues.
